version: '3.9'

services:
  db:
    image: 'postgres:14.5-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=decks
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
